# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlidingPuzzle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlidingPuzzle
  
  pod "paper-onboarding"
  pod "PKHUD", "~> 5.0"
  pod "SwiftyGif", :git => "https://github.com/kirualex/SwiftyGif", :branch => "swift4"
end
